### ISSUE TITLE
Problems with encodings, umlauts and message parsing

### ISSUE THREAD

**Issue by badboy** [xmpp4r/xmpp4r#13]
At first, thanks. I discovered today that someone took over the maintainership of xmpp4r. This is awesome. I still use xmpp4r with [jabbot](https://github.com/badboy/jabbot) for 2 small bots. But this only really works with Ruby 1.8, which is dead.

So now I tried using it with my bot and I immediately had some issues.
When jabbot receives a message containing umlauts (or other non-ascii characters) it aborts.

```

[#<REXML::ParseException: #<Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)>
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rexml/source.rb:212:in `match'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rexml/source.rb:212:in `match'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:419:in `pull_event'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rexml/parsers/baseparser.rb:183:in `pull'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rexml/parsers/sax2parser.rb:92:in `parse'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/xmpp4r-0.5.5/lib/xmpp4r/streamparser.rb:79:in `parse'
/home/badboy/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/xmpp4r-0.5.5/lib/xmpp4r/stream.rb:75:in `block in start'
...
Exception parsing
Line: 
Position: 0
Last 80 unconsumed characters:
✓✗</body>>, #<Jabber::Client:0x00000003160730 @fd=#<OpenSSL::SSL::SSLSocket:0x00000002d5db38>, @status=1, @xmlcbs=#<Jabber::CallbackList:0x00000003160708 @list=[]>, @stanzacbs=#<Jabber::CallbackList:0x00000003160690 @list=[]>, @messagecbs=#<Jabber::CallbackList:0x00000003160640 @list=[#<Jabber::Callback 150 #<Jabber::MUC::SimpleMUCClient:0x00000001ded888>>]>, @iqcbs=#<Jabber::CallbackList:0x000000031605f0 @list=[]>, @presencecbs=#<Jabber::CallbackList:0x00000003160578 @list=[#<Jabber::Callback 150 #<Jabber::MUC::SimpleMUCClient:0x00000001ded888>>]>, @send_lock=#<Mutex:0x00000003160528>, @last_send=2013-10-15 16:55:37 +0200, @exception_block=#<Proc:0x00000003160320@/home/badboy/projects/jabbot_live/bot/jabbot/lib/jabbot/bot.rb:105>, @tbcbmutex=#<Mutex:0x000000031604d8>, @threadblocks=[], @wakeup_thread=nil, @streamid="3733782154", @streamns="jabber:client", @features_sem=#<Jabber::Semaphore:0x00000003160460 @tickets=0, @lock=#<Mutex:0x00000003160438>, @cond=#<ConditionVariable:0x00000003160410 @waiters=[], @waiters_mutex=#<Mutex:0x00000003160398>>>, @parser_thread=#<Thread:0x00000002f18978 dead>, @processing=0, @host="myserver", @port=5222, @allow_tls="constant", @tls=true, @ssl_capath=nil, @ssl_verifycb=nil, @features_timeout=10, @keepalive_interval=60, @use_ssl=false, @jid=user@myserver/jabbot, @authenticated=true, @socket=#<OpenSSL::SSL::SSLSocket:0x00000002d5db38>, @stream_mechanisms=[], @stream_features={"bind"=>"urn:ietf:params:xml:ns:xmpp-bind", "session"=>"urn:ietf:params:xml:ns:xmpp-session", "c"=>"http://jabber.org/protocol/caps", "register"=>"http://jabber.org/features/iq-register"}, @parser=#<Jabber::StreamParser:0x00000002f189a0 @stream=#<OpenSSL::SSL::SSLSocket:0x00000002d5db38>, @listener=#<Jabber::Client:0x00000003160730 ...>, @current=<body/>, @started=true>, @keepaliveThread=#<Thread:0x00000002f1f390 dead>>, :parser]
exiting...
```

I got it to work when patching `rexml/source.rb` with:

``` ruby
    def match( pattern, cons=false )
      rv = pattern.match(@buffer.force_encoding("UTF-8"))
```

Of course this is hacky and not even in xmpp4r itself.

What I know (I didn't read much of the code): xmpp4r does not consider any encoding and reading from a TCPSocket returns ASCII-Bit if not set otherwise. Any chance this can be handled in xmpp4r?

**Comment by snan** [comment]
#15 isn't enough, I still get the issue.

**Comment by snan** [comment]
> Initially, strings from the stream are correctly detected as UTF-8, only when an actual UTF-8 string is read from the socket does the encoding change to ASCII-8BIT. 

I get exactly this behavior
