### ISSUE TITLE
auth mechanism error

### ISSUE THREAD

**Issue by uranio-235** [xmpp4r/xmpp4r#44]
Hi there, I have following error, after

Im.auth() using the correct password of course

```
irb(main):077:0> Im.auth('*******')
D, [2015-10-20T12:03:21.919224 #19455] DEBUG -- : SENDING:
    <auth mechanism='PLAIN' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>bGF6YXJvYXJtYW5kb0BpbmZvbWVkLnNsZC5jdQBsYXphcm9hcm1hbmRvAGxhemFybzg4MTAxNg==</auth>
D, [2015-10-20T12:03:21.963056 #19455] DEBUG -- : RECEIVED:
    <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-authorized/></failure>
D, [2015-10-20T12:03:21.964132 #19455] DEBUG -- : RuntimeError: not-authorized
    /home/lazaro/.gem/ruby/2.2.0/gems/xmpp4r-0.5.6/lib/xmpp4r/sasl.rb:69:in `auth'
    /home/lazaro/.gem/ruby/2.2.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:176:in `auth_sasl'
    /home/lazaro/.gem/ruby/2.2.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:113:in `auth'
    (irb):77:in `irb_binding'
    /usr/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
    /usr/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
    /usr/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
    /usr/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
    /usr/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
    /usr/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'
    /usr/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'
    /usr/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
    /usr/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
    /usr/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
    /usr/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
    /usr/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
    /usr/lib/ruby/2.2.0/irb.rb:395:in `block in start'
    /usr/lib/ruby/2.2.0/irb.rb:394:in `catch'
    /usr/lib/ruby/2.2.0/irb.rb:394:in `start'
    /usr/bin/irb:11:in `<main>'
Jabber::ClientAuthenticationFailure: not-authorized
	from /home/lazaro/.gem/ruby/2.2.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:120:in `rescue in auth'
	from /home/lazaro/.gem/ruby/2.2.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:109:in `auth'
	from (irb):77
	from /usr/bin/irb:11:in `<main>'

```

**Comment by mchristen** [comment]
@uranio-235 FWIW even though you masked your password with '****' in your Im.auth() call, your password is still in plaintext(albeit base64 encoded) in the debug output.
