### ISSUE TITLE
Getting Deadlock Issue

### ISSUE THREAD

**Issue by ankitkr** [xmpp4r/xmpp4r#46]
No live threads left. Deadlock?
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `sleep'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `wait'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `block in wait'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `synchronize'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `wait'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:331:in `wait'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:398:in `send'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:89:in `start'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:205:in `restart'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:179:in `auth_sasl'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:111:in `auth'

**Comment by ankitkr** [comment]
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/source.rb:235: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0009 p:---- s:0067 e:000066 CFUNC  :eof?
c:0008 p:0026 s:0064 e:000063 METHOD /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/source.rb:235
c:0007 p:0009 s:0061 e:000060 METHOD /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:148
c:0006 p:0038 s:0058 e:000057 METHOD /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:196
c:0005 p:0007 s:0027 e:000026 METHOD /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:184
c:0004 p:0037 s:0024 E:001058 METHOD /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/sax2parser.rb:92
c:0003 p:0082 s:0010 E:001370 METHOD /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91
c:0002 p:0027 s:0005 e:000004 BLOCK  /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75 [FINISH]
c:0001 p:---- s:0002 e:000001 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91:in `parse'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/sax2parser.rb:92:in `parse'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:184:in `pull'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:196:in `pull_event'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:148:in `empty?'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/source.rb:235:in `empty?'
/home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/source.rb:235:in `eof?'

**Comment by ankitkr** [comment]
W, [2015-11-02T18:49:50.854131 #11927]  WARN -- : EXCEPTION:
    REXML::UndefinedNamespaceException
    Undefined prefix stream found
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:413:in `block in pull_event'
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/set.rb:283:in `each_key'
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/set.rb:283:in `each'
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:411:in `pull_event'
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/baseparser.rb:184:in `pull'
    /home/ubuntu/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rexml/parsers/sax2parser.rb:92:in `parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:91:in `parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
W, [2015-11-02T18:49:50.854234 #11927]  WARN -- : EXCEPTION:
    TypeError
    no implicit conversion of REXML::UndefinedNamespaceException into String
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:137:in `+'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:137:in `parse_failure'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:93:in `rescue in parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:38:in `parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
W, [2015-11-02T18:49:50.854264 #11927]  WARN -- : Exception caught in Parser thread! (TypeError)
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:137:in `+'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:137:in `parse_failure'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:93:in `rescue in parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/streamparser.rb:38:in `parse'
    /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:75:in `block in start'
/home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `sleep': No live threads left. Deadlock? (fatal)
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `wait'
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `block in wait'
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `synchronize'
        from /home/ubuntu/.rvm/gems/ruby-2.2.1/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `wait'

**Comment by virtadpt** [comment]
Nobody else gets this error, I guess?
