### ISSUE TITLE
fatal: No live threads left. Deadlock?

### ISSUE THREAD

**Issue by chenghung** [xmpp4r/xmpp4r#50]
I got a no live thread left error when trying connect to xmpp server.
My ruby version is 2.1.5.

below logs are exception backtraces
```
fatal: No live threads left. Deadlock?
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `sleep'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `wait'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:24:in `block in wait'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `synchronize'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/semaphore.rb:23:in `wait'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:331:in `wait'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:398:in `send'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:89:in `start'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:185:in `starttls'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:121:in `accept_features'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:89:in `connect'
	from /opt/www/zooti/shared/bundle/ruby/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:71:in `connect'
```

**Comment by Bodata** [comment]
Same problem here.  I am trying to make a work around. 
The problem seems, once in a while the connection call hangs. 
Not clear why, but it happens after a (re)start  in starttls.
I have now made a version with a timeout around the start, and when there is a failure it set @status=1 (Disconnected).
In my code i check if there is a connection, if not i retry the connection, seems to connect the second time without problems.  
I hope to add a pull request, but i am a first timer with github.

Regards,
Peter.

**Comment by Bodata** [comment]
Ok, i have added the pull request... #51
Can anyone explain to me how, if ever, it wil get in the gem i use in the rails project ?

**Comment by iamsimakov** [comment]
just use `begin` ... `rescue` in any callbacks such as `add_message_callback` and others
